### ISSUE TITLE
Releasing vanilla LSTM pre-trained LM model?

### ISSUE THREAD

**Issue by GaryYufei** [LiyuanLucasLiu/LD-Net#13]
Hi, thanks for this great work. It is very helpful to release the pre-trained LM in such a clear code (unlike Elmo)

I am wondering if you have any plan to release the pre-trained R-Elmo model in your paper (#6 and #7 in table 1 of the paper)?

Thanks!

**Comment by LiyuanLucasLiu** [comment]
Thanks for your interest and sorry for the late of reply. We are working on some submissions in the last week. As to the pre-trained Elmo models, unfortunately, we have deleted these models :(
