### ISSUE TITLE
Do you think we can edit transformer to dense structure like LD-Net?

### ISSUE THREAD

**Issue by guotong1988** [LiyuanLucasLiu/LD-Net#9]
https://github.com/divelab/dtn 
Is the link I want?
@LiyuanLucasLiu 
Thank you very much!

**Comment by LiyuanLucasLiu** [comment]
Emmm, i think it would be better to discuss such topics via email or IMs, since issues here are supposed to be related to the `LD-Net` model only. Thanks for your understanding :- )
